# template for creating a new benchmark tier pod

apiVersion: v1
kind: Pod
metadata:
  name: benchmark-pod-NUM_DUMMY
  labels: 
    role: benchmark
spec:
  containers:
  - name: benchmark-container
    image: vsreekanti/kvs
    env: 
    - name: SERVER_TYPE
      value: b
    - name: PROXY_IPS
      value: PROXY_IPS_DUMMY
    - name: MON_IP
      value: MON_IP_DUMMY
  nodeSelector:
    role: benchmark
    podid: benchmark-NUM_DUMMY
