apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod-NUM_DUMMY
  labels: 
    role: ebs
spec:
  containers:
    - name: kvs-ebs-container
      image: cgwu/kvs
      env: 
      - name: SERVER_TYPE
        value: "2"
      - name: PROXY_IPS
        value: PROXY_IPS_DUMMY
      - name: SEED_SERVER
        value: SEED_SERVER_DUMMY
      - name: MON_IP
        value: MON_IP_DUMMY
      volumeMounts:
      - mountPath: /ebs/ebs_0
        name: ebs0
  nodeSelector:
    role: ebs
  volumes:
  - name: ebs0
    awsElasticBlockStore:
      volumeID: VOLUME_DUMMY_0
      fsType: ext4
  restartPolicy: Never
