apiVersion: v1
kind: Pod
metadata:
  name: monitoring-pod
  labels: 
    role: monitoring
spec:
  containers:
  - name: kvs-monitoring-container
    image: vsreekanti/kvs
    env: 
    - name: SERVER_TYPE
      value: mn
  nodeSelector:
    role: general
