apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
  labels: 
    role: proxy
spec:
  containers:
  - name: kvs-proxy-container
    image: vsreekanti/kvs
    env: 
    - name: SERVER_TYPE
      value: p
  nodeSelector:
    role: proxy
