# template for creating a new routing pod

apiVersion: v1
kind: Pod
metadata:
  name: routing-pod-NUM_DUMMY
  labels: 
    role: routing
spec:
  containers:
  - name: routing-container
    image: vsreekanti/kvs
    env: 
    - name: SERVER_TYPE
      value: r
    - name: MON_IP
      value: MON_IP_DUMMY
  nodeSelector:
    role: routing
    podid: routing-NUM_DUMMY
  restartPolicy: Never
