monitoring:
  mgmt_ip: 127.0.0.1
  ip: 127.0.0.1
routing:
  monitoring_ip: 127.0.0.1
  ip: 127.0.0.1
user:
  monitoring_ip: 127.0.0.1
  routing_ips: 
      - 127.0.0.1
  ip: 127.0.0.1
server:
  monitoring_ip: 127.0.0.1
  routing_ips: 
      - 127.0.0.1
  seed_ip: 127.0.0.1
  ip: 127.0.0.1
ebs: ./
thread:
  memory: 4
  ebs: 4
  routing: 4
replication:
  memory: 1
  ebs: 0
  minimum: 1
  local: 1