apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: benchmark-instances
spec:
  image: 889180461196/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-08-21
  machineType: m4.4xlarge
  maxSize: NUM_DUMMY
  minSize: NUM_DUMMY
  role: Node
  rootVolumeSize: 32
  nodeLabels:
    role: benchmark
  subnets:
    - us-east-1a

