apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: benchmark-instances
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: r4.8xlarge
  maxSize: NUM_DUMMY
  minSize: NUM_DUMMY
  role: Node
  rootVolumeSize: 32
  nodeLabels:
    role: benchmark
  subnets:
    - us-east-1a
