# template for creating a new memory tier node

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: ebs-instances
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-08-21
  machineType: m4.large
  maxSize: NUM_DUMMY
  minSize: NUM_DUMMY
  rootVolumeSize: 32
  role: Node
  nodeLabels:
    role: ebs
  subnets:
    - us-east-1a
